In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

# 定义数据

In [3]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
print(features.shape, labels.shape)

torch.Size([1000, 2]) torch.Size([1000, 1])


# 使用torch的dataloader

In [4]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [5]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [9]:
from collections import abc
print(isinstance(data_iter, abc.Iterable))
print(isinstance(data_iter, abc.Iterator))

True
False


In [10]:
len(data_iter)

100

In [12]:
test_x, test_y = next(iter(data_iter))
print(test_x, test_y)

tensor([[-0.9751,  0.5965],
        [-1.2753, -0.7557],
        [-0.2709, -0.3327],
        [-1.9259, -0.9318],
        [-1.9812, -0.5369],
        [ 0.7181, -0.2470],
        [-0.1015,  0.2408],
        [-0.4564, -0.8654],
        [ 1.0131, -0.0592],
        [-0.1876, -1.0624]]) tensor([[0.2146],
        [4.2315],
        [4.7846],
        [3.5228],
        [2.0758],
        [6.4618],
        [3.1763],
        [6.2434],
        [6.4302],
        [7.4330]])


In [15]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [16]:
print(dir(net))

['T_destination', '__add__', '__annotations__', '__call__', '__class__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_buffers', '_call_impl', '_forward_hooks', '_forward_pre_hooks', '_get_backward_hooks', '_get_item_by_idx', '_get_name', '_is_full_backward_hook', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backward_hook', '_modules', '_named_members', '_non_persistent_buffers_set', '_parameters', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_repl

In [20]:
print(len(net))
print(type(net))
print(type(net[0]))
print(isinstance(net, abc.Iterable))
print(isinstance(net, abc.Iterator))

1
<class 'torch.nn.modules.container.Sequential'>
<class 'torch.nn.modules.linear.Linear'>
True
False


In [54]:
# print(dir(net[0]))
print(net[0].weight.shape, net[0].bias.shape)
print(net[0].weight.data, net[0].bias.data)
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)
print(net[0].weight.data, net[0].bias.data)

torch.Size([1, 2]) torch.Size([1])
tensor([[0.6793, 0.3626]]) tensor([-0.3012])
tensor([[0.0023, 0.0035]]) tensor([0.])


In [61]:
print(next(net.parameters()))
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[0.0023, 0.0035]], requires_grad=True)
Parameter containing:
tensor([[0.0023, 0.0035]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [66]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.3)
isinstance(loss, abc.Iterable)

False

In [69]:
import tqdm

ModuleNotFoundError: No module named 'tqdm'

In [68]:
num_epochs = 3
for epoch in range(num_epochs):
    for x_batch, y_batch in data_iter:
        l = loss(net(x_batch), y_batch)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
        
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')


epoch 1, loss 0.000107
epoch 2, loss 0.000100
epoch 3, loss 0.000117


In [ ]:
print(true_w, '\n', net[0].weight.data)

In [25]:
print(net[0].forward(test_x).shape)

torch.Size([10, 1])


In [71]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = a.detach()
print(hex(id(a)), hex(id(b)))
print(hex(a.data_ptr()) == hex(b.data_ptr()))

0x7fe38e436ad0 0x7fe38e436bf0
True


Parameter containing:
tensor([[0.0023, 0.0035]], requires_grad=True)


In [73]:
model = nn.Linear(2, 1)
model.weight.data.normal_(0, 0.01)
model.bias.data.fill_(0)

optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)
num_epochs = 3
for epoch in range(num_epochs):
    for x_batch, y_batch in data_iter:
        l = loss(model(x_batch), y_batch)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    
    l = loss(model(features), labels)
    print(f'epoch {epoch + 1}, loss {l:}')

epoch 1, loss 0.00010356200073147193
epoch 2, loss 0.00011207385978195816
epoch 3, loss 0.00010679661500034854
