In [1]:
import os
import datetime
from torch.utils.tensorboard import SummaryWriter

class Logger(object):
    def __init__(self, log_dir, log_hist=True):
        """Create a summary writer logging to log_dir."""
        if log_hist:    # Check a new folder for each log should be dreated
            log_dir = os.path.join(
                log_dir,
                datetime.datetime.now().strftime("%Y_%m_%d__%H_%M_%S"))
        self.writer = SummaryWriter(log_dir)

    def scalar_summary(self, tag, value, step):
        """Log a scalar variable."""
        self.writer.add_scalar(tag, value, step)

    def list_of_scalars_summary(self, tag_value_pairs, step):
        """Log scalar variables."""
        for tag, value in tag_value_pairs:
            self.writer.add_scalar(tag, value, step)


ModuleNotFoundError: No module named 'tensorboard'

In [2]:
logger = Logger("./")

In [5]:
import torch
for i in range(5):
    random_tensor = torch.rand(3, 3)
    print(random_tensor)
    logger.scalar_summary("RandomTensor", random_tensor.sum(), i)

tensor([[0.6784, 0.6819, 0.0779],
        [0.6244, 0.1509, 0.4386],
        [0.0016, 0.8810, 0.6941]])
tensor([[0.2240, 0.0017, 0.2318],
        [0.2486, 0.1422, 0.1606],
        [0.5572, 0.9028, 0.2851]])
tensor([[0.8816, 0.3422, 0.2116],
        [0.0943, 0.1157, 0.6556],
        [0.3265, 0.2396, 0.6239]])
tensor([[0.7432, 0.9917, 0.9565],
        [0.3096, 0.8468, 0.5555],
        [0.5297, 0.5470, 0.4385]])
tensor([[0.0656, 0.8717, 0.8911],
        [0.3291, 0.6991, 0.3101],
        [0.9069, 0.7434, 0.5202]])


In [7]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.4750, 0.9040, 0.1002],
        [0.7159, 0.2413, 0.4616],
        [0.0056, 0.8019, 0.0550]])

In [8]:
random_tensor.clamp(0)

tensor([[0.4750, 0.9040, 0.1002],
        [0.7159, 0.2413, 0.4616],
        [0.0056, 0.8019, 0.0550]])

In [27]:
torch.manual_seed(2)
torch.rand(3, 3)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190],
        [0.4425, 0.0958, 0.6142]])

In [29]:
torch.rand(3, 3)

tensor([[0.3078, 0.9809, 0.0103],
        [0.4660, 0.4604, 0.8547],
        [0.4525, 0.6317, 0.4760]])